# Generated by Django 4.0 on 2022-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_d', models.CharField(max_length=30)),
                ('phone_d', models.IntegerField()),
                ('location_d', models.CharField(max_length=30)),
                ('email_d', models.CharField(max_length=50)),
                ('cidnew_d', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=30)),
                ('phone_post', models.IntegerField()),
                ('location_post', models.CharField(max_length=30)),
                ('email_post', models.CharField(max_length=50)),
                ('cidnew_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buypre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pre', models.CharField(max_length=30)),
                ('phone_pre', models.IntegerField()),
                ('location_pre', models.CharField(max_length=30)),
                ('email_pre', models.CharField(max_length=50)),
                ('cidnew_pre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donglerecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField()),
                ('d_plan', models.CharField(max_length=40)),
                ('d_validity', models.CharField(max_length=50)),
                ('d_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Postrecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('post_plan', models.CharField(max_length=40)),
                ('post_validity', models.CharField(max_length=50)),
                ('post_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prerecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_id', models.IntegerField()),
                ('pre_plan', models.CharField(max_length=40)),
                ('pre_validity', models.CharField(max_length=50)),
                ('pre_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rechargedongle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_d', models.IntegerField()),
                ('cid_d', models.IntegerField()),
                ('cname_d', models.CharField(max_length=50)),
                ('amount_d', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rechargepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_post', models.IntegerField()),
                ('cid_post', models.IntegerField()),
                ('cname_post', models.CharField(max_length=50)),
                ('amount_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rechargepre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_pre', models.IntegerField()),
                ('cid_pre', models.IntegerField()),
                ('cname_pre', models.CharField(max_length=50)),
                ('amount_pre', models.IntegerField()),
            ],
        ),
    ]
